name: Master CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version:  16.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          LOGGER: "false"
          RECOVER_ATTEMPT_DURATION: "2"
          RECOVER_INTERVAL: "1"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy
    needs: [ build-test ]
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY_1}}
          heroku_app_name: "switcher-load-balance"
          heroku_email: ${{secrets.HEROKU_EMAIL_1}}